# Generated by Django 6.0.6 on 2026-06-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encadreurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_achetes', models.PositiveIntegerField(default=3)),
                ('montant', models.PositiveIntegerField(help_text='Montant payé en FCFA')),
                ('token_paydunya', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_achats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat de crédits',
                'verbose_name_plural': 'Achats de crédits',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('type', models.CharField(choices=[('cours_mois', 'Cours au mois'), ('cours_horaire', "Cours à l'heure")], default='cours_mois', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('token_paydunya', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to='encadreurs.profilencadreur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_emis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CreditUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations', to='paiement.creditachat')),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_consommes', to='encadreurs.profilencadreur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits_utilises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation de crédit',
                'verbose_name_plural': 'Utilisations de crédits',
                'unique_together': {('parent', 'encadreur')},
            },
        ),
    ]
