# Generated by Django 6.0.6 on 2026-06-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='ProfilEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('tarif_mois', models.PositiveIntegerField(blank=True, help_text='Tarif mensuel en FCFA', null=True)),
                ('tarif_horaire', models.PositiveIntegerField(blank=True, help_text='Tarif horaire en FCFA', null=True)),
                ('type_tarif', models.CharField(choices=[('mois', 'Au mois'), ('horaire', "À l'heure"), ('les_deux', 'Les deux')], default='mois', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('accepte_deplacement', models.BooleanField(default=False)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('bac_en_cours', 'BAC en cours'), ('bac', 'BAC'), ('bac_plus_1', 'BAC+1'), ('bac_plus_2', 'BAC+2'), ('bac_plus_3', 'BAC+3'), ('bac_plus_4', 'BAC+4'), ('bac_plus_5', 'BAC+5'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], default='', max_length=20)),
                ('niveaux_enseignement', models.JSONField(blank=True, default=list)),
                ('experience_cours', models.CharField(blank=True, choices=[('regulier', 'Oui, régulièrement'), ('occasionnel', 'Oui, occasionnellement'), ('premiere_fois', 'Non, ce sera ma première fois')], default='', max_length=20)),
                ('jours_disponibles', models.JSONField(blank=True, default=list)),
                ('creneaux_preferes', models.JSONField(blank=True, default=list)),
                ('cgu_acceptees', models.BooleanField(default=False)),
                ('questionnaire_rempli', models.BooleanField(default=False)),
                ('matieres', models.ManyToManyField(blank=True, related_name='encadreurs', to='encadreurs.matiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_encadreur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil encadreur',
                'verbose_name_plural': 'Profils encadreurs',
            },
        ),
    ]
