# Generated by Django 6.0.6 on 2026-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encadreurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilencadreur',
            name='autre_matiere',
            field=models.CharField(blank=True, default='', help_text="Autre matière (si 'Autre' est sélectionné)", max_length=200),
        ),
    ]
