# Generated by Django 6.0.6 on 2026-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encadreurs', '0002_profilencadreur_autre_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilencadreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='encadreurs/'),
        ),
    ]
