# Generated by Django 6.0.5 on 2026-05-22 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +225XXXXXXXXXX', regex='^\\+225\\d{10}$')]),
        ),
    ]
