# Generated by Django 6.0.5 on 2026-05-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='ProfilEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('tarif_mois', models.PositiveIntegerField(blank=True, help_text='Tarif mensuel en FCFA', null=True)),
                ('tarif_horaire', models.PositiveIntegerField(blank=True, help_text='Tarif horaire en FCFA', null=True)),
                ('type_tarif', models.CharField(choices=[('mois', 'Au mois'), ('horaire', "À l'heure"), ('les_deux', 'Les deux')], default='mois', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('matieres', models.ManyToManyField(blank=True, related_name='encadreurs', to='core.matiere')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_encadreur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil encadreur',
                'verbose_name_plural': 'Profils encadreurs',
            },
        ),
    ]
