# Generated by Django 6.0.2 on 2026-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilencadreur',
            name='accepte_deplacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='cgu_acceptees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='creneaux_preferes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='experience_cours',
            field=models.CharField(blank=True, choices=[('regulier', 'Oui, régulièrement'), ('occasionnel', 'Oui, occasionnellement'), ('premiere_fois', 'Non, ce sera ma première fois')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='jours_disponibles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='niveau_etudes',
            field=models.CharField(blank=True, choices=[('bac_en_cours', 'BAC en cours'), ('bac', 'BAC'), ('bac_plus_1', 'BAC+1'), ('bac_plus_2', 'BAC+2'), ('bac_plus_3', 'BAC+3'), ('bac_plus_4', 'BAC+4'), ('bac_plus_5', 'BAC+5'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='niveaux_enseignement',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='questionnaire_rempli',
            field=models.BooleanField(default=False),
        ),
    ]
