# Generated by Django 6.0.2 on 2026-05-23 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilencadreur',
            name='nombre_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'Nouveau message'), ('profile_verified', 'Profil vérifié'), ('new_review', 'Nouvel avis')], max_length=30),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(help_text='Note de 1 à 5')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to='core.profilencadreur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ('-created_at',),
                'unique_together': {('parent', 'encadreur')},
            },
        ),
    ]
