# Generated by Django 6.0.2 on 2026-05-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profilencadreur_nombre_avis_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'Nouveau message'), ('profile_verified', 'Profil vérifié'), ('new_review', 'Nouvel avis'), ('payment_received', 'Paiement reçu')], max_length=30),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(help_text='Montant en FCFA')),
                ('type', models.CharField(choices=[('cours_mois', 'Cours au mois'), ('cours_horaire', "Cours à l'heure")], default='cours_mois', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Complété'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('token_paydunya', models.CharField(blank=True, default='', max_length=100)),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to='core.profilencadreur')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_emis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ('-created_at',),
            },
        ),
    ]
